### ISSUE TITLE
Failed: javascript error: uiveri5 is not definedReferenceError: uiveri5 is not defined

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-uiveri5#77] opened 2019-05-29 05:14 UTC
Hi Maxim,
After performing any CRUD operation on the UI5 website using uiveri5, the uiveri5 loses its context. I am getting below because of that.

INFO: Expectation FAILED: Failed: javascript error: uiveri5 is not definedReferenceError: uiveri5 is not defined
    at findByControl (<anonymous>:364:5)
    at <anonymous>:388:6
    at callFunction (<anonymous>:352:33)
    at <anonymous>:362:23
    at <anonymous>:363:3
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.5 x86_64)

**Comment by impnguyen** [comment] 2019-05-29 06:57
I have the same issue if I try to access a control via Locator.

**Comment by tsaleksandrova** [comment] 2019-05-29 07:26
Hi,
please include the full test execution log in verbose mode

**Comment by maximnaidenov** [comment] 2019-05-29 12:21
Hi  Nipun,
the message actually means there are no uiveri5 scripts defined and there are two common reasons. 
1. your authentication is failing and timeout and your test does not actually open your app. This could be observed in the screenshot report.
2. You get this while the test is working but at a very specific step like some external navigation, language change or user change. This would mean that your application is doing page refresh or browser redirect. Both of those are totally against the architecture of a SPA and uiveri5 does not support them currently. 
So please attach full execution report, script and logs with -v  and connection details - url,user/pass so we could diagnose that is happening.

**Comment by nipun0212** [comment] 2019-05-29 13:27
[Archive.zip](https://github.com/SAP/ui5-uiveri5/files/3232665/Archive.zip)
Hi Maxim,

Please find the logs in the attachment.
To login and check please follow below steps

Navigate to https://swapaas.webanalytics.cfapps.sap.hana.ondemand.com/index.html
Click on useridp
Give username = nipun.madan@sap.com
Give password = Shiv_1989
Click on Logon
Click on Administartorà Click on spaceManagement
 
The spec file and conf.js is also attached
[Archive.zip](https://github.com/SAP/ui5-uiveri5/files/3232660/Archive.zip)

**Comment by impnguyen** [comment] 2019-05-29 14:27
@maximnaidenov in my case it was the second aspect. I forced a redirection after an authentication request.
 
This does not work
`browser.get('.../index.html');`

but this works (even if you switch to another url):
`      return browser.testrunner.navigation.to('.../index.html', {auth:'plain'});
`

**Comment by maximnaidenov** [comment] 2019-05-30 05:27
Hi Manh,
this is by design. Please note that programmatic authentication is intended for more advanced e2e scenarious, much better to use declarative authentication using the baseUrl for simple scenarios.

**Comment by maximnaidenov** [comment] 2019-05-31 06:49
Hi Nipun,
as explained several times now, we do not support this part "Click on useridp" in the authenticator for now. So your test actually doesn't pass over the login step and fails there. The message says exactyl this - there is no ui5 on the login page. We are working on a sollution: https://github.com/SAP/ui5-uiveri5/pull/66 but will take some more time, like 2 weeks. A workaround  is to configure the app to work without this "click on useridp" step in the login.

**Comment by maximnaidenov** [comment] 2019-06-03 08:49
Closing this issue as the problem was caused by wrong webdriver.

**Closed by maximnaidenov** 2019-06-03 08:49 UTC

**Comment by maximnaidenov** [comment] 2019-06-19 12:44
Hi Nipin, we finally released the IDP support feature: https://github.com/SAP/ui5-uiveri5/releases/tag/v1.39.0
