### ISSUE TITLE
E/launcher - Process exited with error code 199

### ISSUE THREAD

**Issue by venkatui5** [SAP/ui5-uiveri5#303] opened 2021-04-02 16:09 UTC
Hi ,

i have followed the instruction of (https://developers.sap.com/tutorials/cp-cicd-sytem-test.html) to run the UIVERI5 application . but I am getting subject line error. Can someone help me to resolve this?
 
below is the log FYI.

$ uiveri5
INFO: @ui5/uiveri5 v1.46.3
INFO: Resolving specs
INFO: Check for latest version of: chromedriver from: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
INFO: Found latest version of chromedriver: 89.0.4389.23
INFO: Downloading webdriver binary: https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
INFO: Executing 1 specs
[10:58:58] I/launcher - Running 1 instances of WebDriver
INFO: Opening webdriver connection with capabilities: {"browserName":"chrome","platform":"LINUX","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]},"count":1,"loggingPrefs":{"browser":"SEVERE"}}
[10:58:58] E/launcher - Server terminated early with status 127
[10:58:58] E/launcher - Error: Server terminated early with status 127
    at /home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/remote/index.js:252:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/selenium-webdriver/chrome.js:761:15)
    at DirectDriverProvider.getNewDriver (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/src/connection/directConnectionProvider.js:522:43)
    at Runner.createBrowser (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:195:43)
    at /home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:834:54)
    at /home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/home/user/.node_modules_global/lib/node_modules/@ui5/uiveri5/node_modules/protractor/node_modules/q/q.js:137:13)
[10:58:58] E/launcher - Process exited with error code 199

**Comment by maximnaidenov** [comment] 2021-04-05 06:41
Hi,
the error message means that the chromedriver could not be started.
Can you please try starting manually the chromedriver from: /home/user/.node_modules_global/lib/node_modules/
I suppose it will throw an error.

**Comment by cvakiitho** [comment] 2021-04-14 11:29
BTW, we have similar issue now when running locally, latest chromedriver is now 90+ version, which is incompatible with latest chrome (89).

**Comment by maximnaidenov** [comment] 2021-04-14 11:59
@cvakiitho This should in intermediate issue till SAPIT push the chrome updates. You could either set a chromedriver version or use a locally supplied one as explained here: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md
But this issue should happen only on developer machines, CICD should always use a fixed chrome/driver version ?

**Comment by cvakiitho** [comment] 2021-04-14 12:01
yep, v90 is not in stable yet. right on dev machines,  CI/CD it should be fixed versions anyway.

**Comment by maximnaidenov** [comment] 2021-04-14 12:08
@cvakiitho It should be, currently UIVeri5 uses: https://chromedriver.storage.googleapis.com/LATEST_RELEASE and it shows 90.0.4430.24

**Comment by cvakiitho** [comment] 2021-04-14 12:40
Yeah sorry I didn't specify, I was talking about chrome v90 https://chromereleases.googleblog.com/ which is not in stable.

**Comment by maximnaidenov** [comment] 2021-04-14 12:54
There is some mess , till now LATEST_RELEASE was always updated on chrome release. And we depend on this for the driver update. If the problem is not fixed soon (like till tomorow) we will need an urgent fix in uiveri5 to return the reading of github file.

**Comment by maximnaidenov** [comment] 2021-04-16 09:10
The mess seems to be fixed now, both local chrome and https://chromedriver.storage.googleapis.com/LATEST_RELEASE are on 90 now so closing the issue.

**Closed by maximnaidenov** 2021-04-16 09:10 UTC
