### ISSUE TITLE
Expectation FAILED: Error: Timeout 

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-uiveri5#144] opened 2019-12-09 04:59 UTC
Hi ,

We are getting below error sometimes

Expectation FAILED: Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

What could be the solution for  the above.

**Comment by maximnaidenov** [comment] 2019-12-09 06:42
This is pretty generic error and is usually caused by system connection issue. Check the screenshot and see what is happening.

**Comment by lpohren** [comment] 2019-12-23 17:46
Hi @nipun0212 ,
When chrome updated to the latest version 79 we started facing this issue as well. 
The fix for us was to increase the default timeouts on our config file, we added this on our file:


`    timeouts: {`
`     getPageTimeout: '100000',`
`      allScriptsTimeout: '110000',`
`      defaultTimeoutInterval: '300000'`
`    }`

**Comment by maximnaidenov** [comment] 2020-01-06 07:47
@lpohren  increasing the timeouts is rarely a solution  and applying it by default, without fully realizing what is the problem is generally not a good idea.

**Comment by lpohren** [comment] 2020-01-06 18:47
@maximnaidenov , 
We were using a very simple code and able to reproduce the issue.
It started happening when Chrome updated to version 79. On our Jenkins, where the version is 76, the timeout changes were not necessary.

Another important point to notice is that this problem was only happening when using authentication, the redirect on it is what triggered the timeout.

**Comment by maximnaidenov** [comment] 2020-01-07 07:08
No further details, closing.

**Closed by maximnaidenov** 2020-01-07 07:08 UTC
