### ISSUE TITLE
Running multiple specs with fiori login, leads to failure at the test procedure

### ISSUE THREAD

**Issue by martenAdrian** [SAP/ui5-uiveri5#68] opened 2019-05-09 05:58 UTC
Wenn running the uiveri5 with:
> conf.js:
```
exports.config = {
    profile: 'visual',
    baseUrl: '----',
    auth: {
        'fiori-form': {user: '---', pass: '---'}
    }
};
```

And multiple \*.spec.js with a single test, like:
```
describe('Check', function () {

    it('Test 2', function () {

        var searchField = element(by.control({
            controlType: "sap.m.SearchField",
            id: /searchField$/,
            interaction: {idSuffix: "I"}
        }));
        var objectListItem = element(by.control({controlType: "sap.m.ObjectListItem"}));
        searchField.sendKeys('Test Positive');
        objectListItem.click();
    });
});
```
 leads to:

```
INFO: Expectation FAILED: Failed: Waiting for auth page to fully load
Wait timed out after 10000ms
INFO: Spec finished: Authentication with status: FAILED
INFO: Suite finished: Automation_Check with status: FAILED for: 12.908s
```
How can i fix this?

**Comment by maximnaidenov** [comment] 2019-05-09 06:18
Hi Marten,
this is a known limitation. Declarative authentication and multiple specs don't work fine (without some manual steps). The problem is that the authentication for the second spec is started but the user still has an active session and so no redirection to IDP will happen.
We have a backlog to address this issue and will work on it in the next months but till then I suggest to use the following workarounds:
1. Use declarative authentication but single spec e.g. structure the suites in modules ( js files but no spec.js) and have single spec.js for usacese e.g. smoketes.spec.js, fulltest.spec.js and always execute a single one.
2. Add a logout step as the last step in every spec.js so the next login will work fine.
2.1 You can use programmatic authentication at the beginning of the spec and log out at the end. This is similar to the previous approach but at leats, it feels more consistent when you look at the spec itself.

**Comment by maximnaidenov** [comment] 2019-06-03 09:34
Closing as this is a feature request that is already covered by our backlog.

**Closed by maximnaidenov** 2019-06-03 09:34 UTC
