### ISSUE TITLE
[Documentation] Global install not working

### ISSUE THREAD

**Issue by frumania** [SAP/ui5-uiveri5#5] opened 2019-01-12 16:14 UTC
Had to run

`npm install @ui5/uiveri5 -g --no-optional`

**Comment by maximnaidenov** [comment] 2019-01-14 07:39
Hi Marcel,

thanks for pointing this problem. I agree with the forgotten -g but the --no-optional seems not necessary any more, it works fine on my machine without it.

**Comment by vobu** [comment] 2019-01-29 12:38
can confirm that `npm i -g @ui5/uiveri5` works out of the box.
env:
- macOS 10.14.2
- npm 6.5.0
- node 11.8.0

**Comment by maximnaidenov** [comment] 2019-06-03 09:41
closing as the issue is not relevant anymore.

**Closed by maximnaidenov** 2019-06-03 09:41 UTC

**Comment by kalmanl** [comment] 2020-10-19 12:06
I still have this issue
tried to install out of the box

> mac 10.15.7
> node v14.10.1
> npm 6.14.8

after installation i get the error `zsh: command not found: uiveri5` when executing  `uiveri5`

**Comment by maximnaidenov** [comment] 2020-10-19 14:29
You should have got an error already while installing ?

**Comment by kalmanl** [comment] 2020-10-20 08:54
Sorry, I had a problem with global NPM installation.
While installing locally `npm install @ui5/uiveri5` it also didn't work, can be a problem on my side, not sure
